app.name=Detective OS
app.version=2.0.1

db.url=jdbc:mysql://localhost:3306/detective_os?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
db.username=detective
db.password=detective123

hibernate.show_sql=false
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update

app.report.directory=reports/generated
