package com.detectiveos.engine;

import com.detectiveos.model.*;
import java.time.*;
import java.util.*;

/** Generates deterministic fictional cases from a seed so demonstrations are repeatable. */
public class CaseGenerator {
    private static final String[] NAMES = {"James Carter", "Sarah Miller", "Robert Blake", "Emily Stone", "David Reed", "Olivia Grant"};
    private static final String[] JOBS = {"Businessman", "Curator", "Security Consultant", "Journalist", "Relative", "Researcher"};

    public CaseFile generate(String title, int seed) {
        Random r = new Random(seed);
        LocalDate date = LocalDate.now().minusDays(r.nextInt(15) + 1L);
        CaseFile c = new CaseFile(title,
                "A fictional locked-room investigation generated by Detective OS. Collect evidence, test statements and reconstruct the timeline before making an accusation.",
                CrimeType.MURDER, "Blackwood Mansion", date, CaseDifficulty.MEDIUM);
        c.setVictim(new Victim("Alexander Reed", 56, "Art Collector"));

        Suspect james = new Suspect(NAMES[0],42,JOBS[0],"Financial dispute","I was in the library from 10:00 PM until 11:00 PM.");
        Suspect sarah = new Suspect(NAMES[1],35,JOBS[1],"Inheritance","I was in the kitchen preparing tea.");
        Suspect robert = new Suspect(NAMES[2],48,JOBS[2],"Professional rivalry","I was near the garden and back entrance.");
        Suspect emily = new Suspect(NAMES[3],31,JOBS[3],"Secret investigation","I was upstairs working on notes.");
        Suspect david = new Suspect(NAMES[4],39,JOBS[4],"Inheritance","I was outside making a phone call.");
        c.addSuspect(james); c.addSuspect(sarah); c.addSuspect(robert); c.addSuspect(emily); c.addSuspect(david);
        c.addWitness(new Witness("Martha Green",61,"Housekeeper","Heard a loud argument before the power outage."));

        LocalDateTime base = LocalDateTime.of(date, LocalTime.of(22,0));
        c.addEvidence(new Evidence("E-001",EvidenceType.CCTV,"Camera captured James Carter entering the kitchen during his claimed library interval.","Kitchen",base.plusMinutes(37),94));
        c.addEvidence(new Evidence("E-002",EvidenceType.PHYSICAL,"Broken glass with a partial fingerprint.","Study",base.plusMinutes(42),75));
        c.addEvidence(new Evidence("E-003",EvidenceType.DOCUMENT,"Torn letter referencing a financial dispute with the victim.","Study",base.plusMinutes(48),92));
        c.addEvidence(new Evidence("E-004",EvidenceType.DIGITAL,"Security log shows the back entrance opened at 22:44.","Back Entrance",base.plusMinutes(44),96));
        c.addEvidence(new Evidence("E-005",EvidenceType.TESTIMONY,"Witness heard an argument shortly before the outage.","Hallway",base.plusMinutes(25),80));

        c.addTimelineEvent(new TimelineEvent(base,"Victim entered the study.","Study",null));
        c.addTimelineEvent(new TimelineEvent(base.plusMinutes(25),"Argument heard by witness involving James Carter.","Hallway",james.getId()));
        c.addTimelineEvent(new TimelineEvent(base.plusMinutes(37),"James Carter entered the kitchen according to CCTV.","Kitchen",james.getId()));
        c.addTimelineEvent(new TimelineEvent(base.plusMinutes(44),"Robert Blake was seen near the back entrance.","Back Entrance",robert.getId()));
        c.addTimelineEvent(new TimelineEvent(base.plusMinutes(51),"Emergency call placed from the study.","Study",null));

        c.addStatement(new Statement(null,james.getName(),james.getAlibi(),base.plusHours(1)));
        c.addStatement(new Statement(null,sarah.getName(),sarah.getAlibi(),base.plusHours(1).plusMinutes(5)));
        c.addStatement(new Statement(null,robert.getName(),robert.getAlibi(),base.plusHours(1).plusMinutes(10)));
        c.addStatement(new Statement(null,emily.getName(),emily.getAlibi(),base.plusHours(1).plusMinutes(15)));
        c.addStatement(new Statement(null,david.getName(),david.getAlibi(),base.plusHours(1).plusMinutes(20)));
        return c;
    }

    public void linkGeneratedSolution(CaseFile c) {
        if (c.getSuspects().isEmpty()) return;
        Suspect culprit = c.getSuspects().get(0);
        c.setSolutionSuspectId(culprit.getId());
        for (Evidence e : c.getEvidence()) {
            if (e.getCode().equals("E-001") || e.getCode().equals("E-003")) e.setLinkedSuspectId(culprit.getId());
        }
        for (TimelineEvent e : c.getTimelineEvents()) {
            if (e.getDescription().contains(culprit.getName())) e.setRelatedPersonId(culprit.getId());
            else if (e.getDescription().contains("Robert Blake") && c.getSuspects().size() > 2) e.setRelatedPersonId(c.getSuspects().get(2).getId());
        }
        for (Statement st : c.getStatements()) {
            c.getSuspects().stream().filter(s -> s.getName().equals(st.getSpeakerName())).findFirst().ifPresent(s -> st.setPersonId(s.getId()));
        }
    }
}
